-- Role de aplicação sem BYPASSRLS. As políticas RLS aplicam-se a este role.
CREATE ROLE obraos_app LOGIN PASSWORD 'obraos_app';
GRANT CONNECT ON DATABASE obraos TO obraos_app;
GRANT USAGE ON SCHEMA public TO obraos_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO obraos_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO obraos_app;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;
